# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: docker
version: 2.6.0
readme: README.md
authors:
  - Ansible Docker Working Group
description: Modules and plugins for working with Docker
license_file: COPYING
tags:
  - docker
repository: https://github.com/ansible-collections/community.docker
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/community.docker
issues: https://github.com/ansible-collections/community.docker/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
