bugfixes:
  - "docker_compose_v2 - handle a (potentially unintentional) breaking change in Docker Compose 2.37.0
     (https://github.com/ansible-collections/community.docker/issues/1082, https://github.com/ansible-collections/community.docker/pull/1083)."
