---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
  - cron: 0 12 * * 0
    displayName: Weekly (old stable branches)
    always: true
    branches:
      include:
        - stable-4

variables:
  - name: checkoutPath
    value: ansible_collections/community/docker
  - name: coverageBranches
    value: main
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:7.0.0

pool: Standard

stages:

### Remote
  - stage: Remote_devel
    displayName: Remote devel
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 10.1 with Docker SDK, urllib3, requests from sources
              test: rhel/10.1-dev-latest
            - name: RHEL 9.7
              test: rhel/9.7
            # For some reason, Ubuntu 24.04 is *extremely* slower than RHEL 9.6
            # - name: Ubuntu 24.04
            #   test: ubuntu/24.04
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5
  - stage: Remote_2_21
    displayName: Remote 2.21
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.21/{0}
          targets:
            - name: RHEL 10.1
              test: rhel/10.1
            # - name: RHEL 9.7
            #   test: rhel/9.7
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5
  - stage: Remote_2_20
    displayName: Remote 2.20
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.20/{0}
          targets:
            - name: RHEL 9.7
              test: rhel/9.7
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5
  - stage: Remote_2_19
    displayName: Remote 2.19
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.19/{0}
          targets:
            - name: Ubuntu 22.04
              test: ubuntu/22.04
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5
  - stage: Remote_2_18
    displayName: Remote 2.18
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.18/{0}
          targets:
            - name: RHEL 9.7
              test: rhel/9.7
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5

  ## Finally

  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Remote_devel
      - Remote_2_21
      - Remote_2_20
      - Remote_2_19
      - Remote_2_18
    jobs:
      - template: templates/coverage.yml
