---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
  - cron: 0 12 * * 0
    displayName: Weekly (old stable branches)
    always: true
    branches:
      include:
        - stable-4

variables:
  - name: checkoutPath
    value: ansible_collections/community/docker
  - name: coverageBranches
    value: main
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:8.0.0

pool: Standard

stages:
  - stage: remote_2_18
    displayName: Remote ansible-core 2.18
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: rhel/9.7 + azp/1/
              test: ansible-test-integration-2.18-rhel-9.7-azp-1
            - name: rhel/9.7 + azp/2/
              test: ansible-test-integration-2.18-rhel-9.7-azp-2
            - name: rhel/9.7 + azp/3/
              test: ansible-test-integration-2.18-rhel-9.7-azp-3
            - name: rhel/9.7 + azp/4/
              test: ansible-test-integration-2.18-rhel-9.7-azp-4
            - name: rhel/9.7 + azp/5/
              test: ansible-test-integration-2.18-rhel-9.7-azp-5

  - stage: remote_2_19
    displayName: Remote ansible-core 2.19
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: ubuntu/22.04 + azp/1/
              test: ansible-test-integration-2.19-ubuntu-22.04-azp-1
            - name: ubuntu/22.04 + azp/2/
              test: ansible-test-integration-2.19-ubuntu-22.04-azp-2
            - name: ubuntu/22.04 + azp/3/
              test: ansible-test-integration-2.19-ubuntu-22.04-azp-3
            - name: ubuntu/22.04 + azp/4/
              test: ansible-test-integration-2.19-ubuntu-22.04-azp-4
            - name: ubuntu/22.04 + azp/5/
              test: ansible-test-integration-2.19-ubuntu-22.04-azp-5

  - stage: remote_2_20
    displayName: Remote ansible-core 2.20
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: rhel/9.7 + azp/1/
              test: ansible-test-integration-2.20-rhel-9.7-azp-1
            - name: rhel/9.7 + azp/2/
              test: ansible-test-integration-2.20-rhel-9.7-azp-2
            - name: rhel/9.7 + azp/3/
              test: ansible-test-integration-2.20-rhel-9.7-azp-3
            - name: rhel/9.7 + azp/4/
              test: ansible-test-integration-2.20-rhel-9.7-azp-4
            - name: rhel/9.7 + azp/5/
              test: ansible-test-integration-2.20-rhel-9.7-azp-5

  - stage: remote_2_21
    displayName: Remote ansible-core 2.21
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: rhel/10.1 + azp/1/
              test: ansible-test-integration-2.21-rhel-10.1-azp-1
            - name: rhel/10.1 + azp/2/
              test: ansible-test-integration-2.21-rhel-10.1-azp-2
            - name: rhel/10.1 + azp/3/
              test: ansible-test-integration-2.21-rhel-10.1-azp-3
            - name: rhel/10.1 + azp/4/
              test: ansible-test-integration-2.21-rhel-10.1-azp-4
            - name: rhel/10.1 + azp/5/
              test: ansible-test-integration-2.21-rhel-10.1-azp-5

  - stage: remote_devel
    displayName: Remote ansible-core devel
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: rhel/10.1 + azp/1/ + sdk-dev-latest
              test: ansible-test-integration-devel-rhel-10.1-azp-1
            - name: rhel/10.1 + azp/2/ + sdk-dev-latest
              test: ansible-test-integration-devel-rhel-10.1-azp-2
            - name: rhel/10.1 + azp/3/ + sdk-dev-latest
              test: ansible-test-integration-devel-rhel-10.1-azp-3
            - name: rhel/10.1 + azp/4/ + sdk-dev-latest
              test: ansible-test-integration-devel-rhel-10.1-azp-4
            - name: rhel/10.1 + azp/5/ + sdk-dev-latest
              test: ansible-test-integration-devel-rhel-10.1-azp-5
            - name: rhel/9.7 + azp/1/
              test: ansible-test-integration-devel-rhel-9.7-azp-1
            - name: rhel/9.7 + azp/2/
              test: ansible-test-integration-devel-rhel-9.7-azp-2
            - name: rhel/9.7 + azp/3/
              test: ansible-test-integration-devel-rhel-9.7-azp-3
            - name: rhel/9.7 + azp/4/
              test: ansible-test-integration-devel-rhel-9.7-azp-4
            - name: rhel/9.7 + azp/5/
              test: ansible-test-integration-devel-rhel-9.7-azp-5

  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - remote_2_18
      - remote_2_19
      - remote_2_20
      - remote_2_21
      - remote_devel
    jobs:
      - template: templates/coverage.yml
